using System.Diagnostics.CodeAnalysis;
using Microsoft.AspNetCore.Mvc;
using Microsoft.OpenApi.Models;
using Swashbuckle.AspNetCore.SwaggerGen;

namespace CaptainHook.Api
{
    /// <summary>
    /// Fixes Swagger definition generated by the <see cref="ProducesDefaultResponseTypeAttribute"/> attribute.
    /// </summary>
    [ExcludeFromCodeCoverage]
    internal class DefaultResponseFixFilter : IOperationFilter
    {
        public void Apply(OpenApiOperation operation, OperationFilterContext context)
        {
            foreach (var response in operation.Responses)
            {
                if (response.Key == "default" && response.Value.Description == null)
                {
                    response.Value.Description = "Unexpected error";
                }
            }
        }
    }
}